<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AssemblyName>Cuelang.Cue.Tests</AssemblyName>
    <RootNamespace>Cuelang.Cue.Tests</RootNamespace>
    <UseTestingPlatform>true</UseTestingPlatform>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cue.Api\Cue.Api.csproj" />
  </ItemGroup>

</Project>