<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <LangVersion>preview</LangVersion>
    <AssemblyName>Cue.Generator.Tests</AssemblyName>
    <RootNamespace>Cue.Generator.Tests</RootNamespace>
    <UseTestingPlatform>true</UseTestingPlatform>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck" Version="3.3.4" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cue.Api\Cue.Api.csproj" />
    <ProjectReference Include="..\Cue.Generator\Cue.Generator.csproj" />
  </ItemGroup>
</Project>
