<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Cuelang.Cue</RootNamespace>
    <LangVersion>preview</LangVersion>
    <AssemblyName>Cuelang.Cue</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\cue.dll" Condition="'$(OS)' == 'Windows_NT'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\libcue.so" Condition="'$(OS)' != 'Windows_NT'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>

